In [3]:
import pandas as pd
recd=pd.read_csv('C:\\Users\\user\\Desktop\\PPK_ELCTY_ATMBL_ELCTC_RECD_Y_2022-01-01_2022-06-30.csv', encoding = 'utf-8-sig')
recd.head(5)

,ELCTC_DTM,CHRSTN_ID,CHRGR_ID,CTPR_CD,SIGNGU_CD,CTPR_NM,SIGNGU_NM,CHRSTN_NM,LA,LO,...,STRT_SOC,END_SOC,SOC_ELCTC_QTY,PWRER_USQNT,ELCTC_TM,PWRER_USQNT_LLD,PWRER_USQNT_MILD,PWRER_USQNT_MXLD,RM,PRDCT_DTM
0,2022-01-01 00:00:02,KRPPKCS0051,KRPPKCP0322,48,123,경상남도,창원시,***** *****,35.187992,128.690885,...,45,100,45.0,124.86,0,124.86,0.0,0.0,2022-09-26 전기차 충전 이력,2022-09-26 18:16:18
1,2022-01-01 00:00:02,KRPPKCS0051,KRPPKCP0325,48,123,경상남도,창원시,***** *****,35.187992,128.690885,...,94,100,94.0,9.24,605,9.24,0.0,0.0,2022-09-26 전기차 충전 이력,2022-09-26 18:16:18
2,2022-01-01 00:00:03,KRPPKCS0051,KRPPKCP0324,48,123,경상남도,창원시,***** *****,35.187992,128.690885,...,80,80,80.0,27.48,1,27.48,0.0,0.0,2022-09-26 전기차 충전 이력,2022-09-26 18:16:18
3,2022-01-01 00:00:03,KRPPKCS0051,KRPPKCP0325,48,123,경상남도,창원시,***** *****,35.187992,128.690885,...,94,100,94.0,9.24,605,9.24,0.0,0.0,2022-09-26 전기차 충전 이력,2022-09-26 18:16:18
4,2022-01-01 00:00:04,KRPPKCS0051,KRPPKCP0321,48,123,경상남도,창원시,***** *****,35.187992,128.690885,...,57,100,57.0,94.44,0,94.44,0.0,0.0,2022-09-26 전기차 충전 이력,2022-09-26 18:16:18

In [4]:
recd.columns

Index(['ELCTC_DTM', 'CHRSTN_ID', 'CHRGR_ID', 'CTPR_CD', 'SIGNGU_CD', 'CTPR_NM',
       'SIGNGU_NM', 'CHRSTN_NM', 'LA', 'LO', 'ELCTC_DV', 'ELCTC_MTHD',
       'STRT_DTM', 'END_DTM', 'STRT_SOC', 'END_SOC', 'SOC_ELCTC_QTY',
       'PWRER_USQNT', 'ELCTC_TM', 'PWRER_USQNT_LLD', 'PWRER_USQNT_MILD',
       'PWRER_USQNT_MXLD', 'RM', 'PRDCT_DTM'],
      dtype='object')

In [6]:
#필요한 컬럼만 추출
recd.drop(columns=['ELCTC_DTM', 'CTPR_CD', 'SIGNGU_CD', 'CTPR_NM',
       'CHRSTN_NM', 'LA', 'LO', 'ELCTC_DV', 'ELCTC_MTHD',
       'STRT_SOC', 'END_SOC', 'SOC_ELCTC_QTY',
       'PWRER_USQNT', 'ELCTC_TM', 'PWRER_USQNT_LLD', 'PWRER_USQNT_MILD',
       'PWRER_USQNT_MXLD', 'RM', 'PRDCT_DTM'],inplace=True)

KeyError: "['ELCTC_DTM', 'CTPR_CD', 'SIGNGU_CD', 'CTPR_NM', 'CHRSTN_NM', 'LA', 'LO', 'ELCTC_DV', 'ELCTC_MTHD', 'STRT_SOC', 'END_SOC', 'SOC_ELCTC_QTY', 'PWRER_USQNT', 'ELCTC_TM', 'PWRER_USQNT_LLD', 'PWRER_USQNT_MILD', 'PWRER_USQNT_MXLD', 'RM', 'PRDCT_DTM'] not found in axis"

In [7]:
경기도=['수원시','성남시','의정부시','안양시','부천시','광명시','평택시','동두천시','안산시','고양시','과천시','구리시','남양주시','오산시','시흥시','군포시','의왕시','하남시','용인시','파주시','이천시','안성시','김포시','화성시','광주시','양주시','포천시','여주시','연천군','가평군','양평군']
recd.drop(index=recd[~recd['SIGNGU_NM'].isin(경기도)].index,inplace=True)

In [8]:
#인덱스 초기화
recd.reset_index(drop=True,inplace=True)
recd

,CHRSTN_ID,CHRGR_ID,SIGNGU_NM,STRT_DTM,END_DTM
0,KRPPKCS0001,KRPPKCP0005,수원시,2022-01-01 00:00:13,2022-01-01 00:27:00
1,KRPPKCS0001,KRPPKCP0009,수원시,2022-01-01 00:00:13,2022-01-01 00:56:59
2,KRPPKCS0001,KRPPKCP0002,수원시,2022-01-01 00:00:14,2022-01-01 01:07:26
3,KRPPKCS0001,KRPPKCP0003,수원시,2022-01-01 00:00:14,2022-01-01 00:23:30
4,KRPPKCS0001,KRPPKCP0007,수원시,2022-01-01 00:00:14,2022-01-01 02:49:21
...,...,...,...,...,...
4759111,KRPPKCS0008,KRPPKCP0487,부천시,2022-06-30 23:17:58,2022-07-01 00:00:01
4759112,KRPPKCS0008,KRPPKCP0049,부천시,2022-06-30 23:54:55,2022-07-01 00:00:00
4759113,KRPPKCS0008,KRPPKCP0064,부천시,2022-06-30 22:57:42,2022-07-01 00:00:00
4759114,KRPPKCS0008,KRPPKCP0049,부천시,2022-06-30 23:54:55,2022-07-01 00:00:00
4759115,KRPPKCS0008,KRPPKCP0487,부천시,2022-06-30 23:17:58,2022-07-01 00:00:01

In [9]:
recd

,CHRSTN_ID,CHRGR_ID,SIGNGU_NM,STRT_DTM,END_DTM
0,KRPPKCS0001,KRPPKCP0005,수원시,2022-01-01 00:00:13,2022-01-01 00:27:00
1,KRPPKCS0001,KRPPKCP0009,수원시,2022-01-01 00:00:13,2022-01-01 00:56:59
2,KRPPKCS0001,KRPPKCP0002,수원시,2022-01-01 00:00:14,2022-01-01 01:07:26
3,KRPPKCS0001,KRPPKCP0003,수원시,2022-01-01 00:00:14,2022-01-01 00:23:30
4,KRPPKCS0001,KRPPKCP0007,수원시,2022-01-01 00:00:14,2022-01-01 02:49:21
...,...,...,...,...,...
4759111,KRPPKCS0008,KRPPKCP0487,부천시,2022-06-30 23:17:58,2022-07-01 00:00:01
4759112,KRPPKCS0008,KRPPKCP0049,부천시,2022-06-30 23:54:55,2022-07-01 00:00:00
4759113,KRPPKCS0008,KRPPKCP0064,부천시,2022-06-30 22:57:42,2022-07-01 00:00:00
4759114,KRPPKCS0008,KRPPKCP0049,부천시,2022-06-30 23:54:55,2022-07-01 00:00:00
4759115,KRPPKCS0008,KRPPKCP0487,부천시,2022-06-30 23:17:58,2022-07-01 00:00:01

In [10]:
recd=recd.drop(columns=['STRT_DTM','END_DTM'])
recd

           CHRSTN_ID     CHRGR_ID SIGNGU_NM
0        KRPPKCS0001  KRPPKCP0005       수원시
1        KRPPKCS0001  KRPPKCP0009       수원시
2        KRPPKCS0001  KRPPKCP0002       수원시
3        KRPPKCS0001  KRPPKCP0003       수원시
4        KRPPKCS0001  KRPPKCP0007       수원시
...              ...          ...       ...
4759111  KRPPKCS0008  KRPPKCP0487       부천시
4759112  KRPPKCS0008  KRPPKCP0049       부천시
4759113  KRPPKCS0008  KRPPKCP0064       부천시
4759114  KRPPKCS0008  KRPPKCP0049       부천시
4759115  KRPPKCS0008  KRPPKCP0487       부천시

[4759116 rows x 3 columns]

In [13]:
recd=recd.groupby('CHRSTN_ID').count()

In [14]:
recd.reset_index(inplace=True)
recd

      CHRSTN_ID  CHRGR_ID  SIGNGU_NM
0   KRPPKCS0001    845247     845247
1   KRPPKCS0002      4175       4175
2   KRPPKCS0003     58530      58530
3   KRPPKCS0005    153395     153395
4   KRPPKCS0007    121167     121167
5   KRPPKCS0008    742620     742620
6   KRPPKCS0011    111860     111860
7   KRPPKCS0012    195513     195513
8   KRPPKCS0016    493167     493167
9   KRPPKCS0020    457717     457717
10  KRPPKCS0021    176313     176313
11  KRPPKCS0022     62556      62556
12  KRPPKCS0061     13609      13609
13  KRPPKCS0062     89487      89487
14  KRPPKCS0064    562113     562113
15  KRPPKCS0065     37998      37998
16  KRPPKCS0066     94677      94677
17  KRPPKCS0067     94201      94201
18  KRPPKCS0068    180212     180212
19  KRPPKCS0069    147368     147368
20  KRPPKCS0070    117191     117191

In [15]:
code_si={'KRPPKCS0001': '수원시',
 'KRPPKCS0021': '시흥시',
 'KRPPKCS0064': '수원시',
 'KRPPKCS0070': '광명시',
 'KRPPKCS0020': '광명시',
 'KRPPKCS0002': '안양시',
 'KRPPKCS0003': '시흥시',
 'KRPPKCS0007': '고양시',
 'KRPPKCS0016': '오산시',
 'KRPPKCS0069': '안양시',
 'KRPPKCS0012': '안양시',
 'KRPPKCS0065': '김포시',
 'KRPPKCS0066': '파주시',
 'KRPPKCS0068': '안양시',
 'KRPPKCS0011': '광명시',
 'KRPPKCS0062': '부천시',
 'KRPPKCS0008': '부천시',
 'KRPPKCS0067': '파주시',
 'KRPPKCS0061': '포천시',
 'KRPPKCS0022': '김포시',
 'KRPPKCS0005': '화성시'}

In [16]:
for idx in recd.index:
    recd.loc[idx,'SIGNGU_NM']=code_si[recd.loc[idx,'CHRSTN_ID']]
    
recd

      CHRSTN_ID  CHRGR_ID SIGNGU_NM
0   KRPPKCS0001    845247       수원시
1   KRPPKCS0002      4175       안양시
2   KRPPKCS0003     58530       시흥시
3   KRPPKCS0005    153395       화성시
4   KRPPKCS0007    121167       고양시
5   KRPPKCS0008    742620       부천시
6   KRPPKCS0011    111860       광명시
7   KRPPKCS0012    195513       안양시
8   KRPPKCS0016    493167       오산시
9   KRPPKCS0020    457717       광명시
10  KRPPKCS0021    176313       시흥시
11  KRPPKCS0022     62556       김포시
12  KRPPKCS0061     13609       포천시
13  KRPPKCS0062     89487       부천시
14  KRPPKCS0064    562113       수원시
15  KRPPKCS0065     37998       김포시
16  KRPPKCS0066     94677       파주시
17  KRPPKCS0067     94201       파주시
18  KRPPKCS0068    180212       안양시
19  KRPPKCS0069    147368       안양시
20  KRPPKCS0070    117191       광명시

In [17]:
recd.rename(columns={'CHRSTN_ID':'충전소','SIGNGU_NM':'시군구','CHRGR_ID':'2022'},inplace=True)

In [19]:
recd=recd[['충전소','시군구','2022']]
recd

            충전소  시군구    2022
0   KRPPKCS0001  수원시  845247
1   KRPPKCS0002  안양시    4175
2   KRPPKCS0003  시흥시   58530
3   KRPPKCS0005  화성시  153395
4   KRPPKCS0007  고양시  121167
5   KRPPKCS0008  부천시  742620
6   KRPPKCS0011  광명시  111860
7   KRPPKCS0012  안양시  195513
8   KRPPKCS0016  오산시  493167
9   KRPPKCS0020  광명시  457717
10  KRPPKCS0021  시흥시  176313
11  KRPPKCS0022  김포시   62556
12  KRPPKCS0061  포천시   13609
13  KRPPKCS0062  부천시   89487
14  KRPPKCS0064  수원시  562113
15  KRPPKCS0065  김포시   37998
16  KRPPKCS0066  파주시   94677
17  KRPPKCS0067  파주시   94201
18  KRPPKCS0068  안양시  180212
19  KRPPKCS0069  안양시  147368
20  KRPPKCS0070  광명시  117191

In [20]:
recd.to_excel('C:\\Users\\user\\Downloads\\충전기 보유 대수.xlsx', encoding = 'utf-8-sig', index = False)